# Generated by Django 5.2.2 on 2025-06-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='province_capital',
        ),
        migrations.AlterField(
            model_name='province',
            name='province_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
