# Generated by Django 5.2.2 on 2025-06-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_province_province_capital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='province_code',
        ),
    ]
