# Generated by Django 5.2.2 on 2025-06-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='province_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
